### ISSUE TITLE
Apos uma derrota(fim de no), o jogo lhe da uma escolha

### ISSUE THREAD

**Issue by CarlosAugustoP** [CarlosAugustoP/atividade-aeds#4]
![image](https://github.com/CarlosAugustoP/atividade-aeds/assets/117591564/b4a29307-f53c-49a8-86de-c787d8357d8d)

**Comment by gabrielpires-1** [comment]
Uma checagem na função game foi adicionada para verificar se o nó tem filhos. Se não tiver, ele printa "FIM DO JOGO" e solicita que o usuário pressione alguma tecla para continuar. Obs: é checado apenas o nó esquerdo, pois, como é uma árvore puramente binária, se existir o nó esquerdo, o direito deve existir. Ou existem 2 nós filhos, ou 0.

Correção:
`if((*t)->esq != NULL){
      //sleep(6);
      if((*t)->esq->esq == NULL){
        printf("\nFIM DO JOGO\n\nPRESSIONE QUALQUER TECLA PARA CONTINUAR");
        getch();
      } else {
        printf("\nINSIRA SUA ESCOLHA: ");
        scanf("%d", &choice);
        if(choice == 1){
            clear();
            //sleep(1);
            game(&((*t)->esq));
        } else {
            clear();
            //sleep(1);
            game(&((*t)->dir));
        }
      }
    }`
